version: "3.9"

services:
  #  example-app:
  #    container_name: example-app
  #    depends_on:
  #      -   example-db
  #    ports:
  #      - "${APP_PORT}:${APP_PORT}"
  #    build:
  #      context: .
  #    environment:
  #      DB_USERNAME: ${DB_USERNAME:?dbUserNameNorProvided}
  #      DB_PASSWORD: ${DB_PASSWORD:?dbPasswordNotProvided}
  #      DB_NAME: ${DB_NAME:?dbNameNotProvided}
  #      DB_HOST: example-db
  #      DB_PORT: 5432
  #      APP_PORT: ${APP_PORT:?appPortNotProvided}
  #    restart: unless-stopped

  example-db:
    container_name: example-db
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=u
      - POSTGRES_PASSWORD=u
      - POSTGRES_DB=u
    restart: unless-stopped