version: "3.9"

services:
  example-db:
    container_name: example-db
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=u
      - POSTGRES_PASSWORD=u
      - POSTGRES_DB=db

  adminer:
    image: adminer
    ports:
      - "8090:8080"