spring:
  liquibase:
    enabled: false
  datasource:
#    url: jdbc:h2:file:./db local
    url: jdbc:postgresql://localhost:5432/db
    username: u
    password: u
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

changeLogFile: classpath:/changelog.yaml
