spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/u
    username: u
    password: u
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
